# Generated by Django 3.1.4 on 2020-12-30 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursery', '0005_customermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='cust_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='plant_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery.plantmodel'),
        ),
    ]
