# Generated by Django 3.1.4 on 2020-12-31 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0008_auto_20201231_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='mobile',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1111111111)]),
        ),
    ]
