# Generated by Django 3.1.4 on 2021-01-01 05:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nursery', '0010_auto_20201231_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('mobile', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1111111111)])),
                ('address', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nursery.customer'),
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
