# Generated by Django 3.1.4 on 2021-01-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0012_auto_20210101_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('nursery', 'nursery')], default='customer', max_length=30),
        ),
    ]
